package com.example.utilities;
public class CompanySymbolList {

public String[] ListTop100() {

	String	Symbols=("ADBE,AMD,ALXN,ALGN,GOOG,CDNS,CDW,CERN,CHTR,CHKP,DXCM,DOCU,DLTR,EBAY,EA,NTAP,NTES,NFLX,NVDA,NXPI,ORLY,PCAR,PAYX,PYPL,PEP,QCOM,REGN,ROST,SGEN,SIRI,SWKS,SPLK,SBUX,SNPS,TMUS,TTWO,TSLA,TXN,KHC,TCOM,ULTA,VRSN,VRSK,WBA,WDC,WDAY,MAR,MXIM,MELI,MCHP,AAN,ACHC,BDC,BIO,CABO,CZR,CDK,DLPH,DPZ,ETSY,EWBC,FDS,FICO,GME,TX,HAE,HELE,ICUI,IDA,NSP,IDCC,JACK,JBL,KBH,KMPR,LAMR,LGND,MASI,MDP,NATI,NEU,OFC,OLED,PBF,PENN,RGEN,ROL,SABR,SAIC,TCBI,TDS,UBSI,UGI,VAC,VLY,WAFD,WEN,XPO,YELP,ZBRA,AX,ELY,FSLY,FRPT,INSP,LPSN,OGI,RDFN,MGNI,TRUP,UPWK,WD,UIS,XBIT,NOG,AWF,KTF,JMP,IRS,TRC,TRU,TWI,UFI,WAL,WMK,XIN,WNC");

String SymbolArr[] = Symbols.split(",");

return SymbolArr;
}
}
		  